print("olá marcelo")
print("como você está?")
print("espero que esteja bem e que tenha um ótimo dia!")
print("se cuida e até mais!")
print("aprendendo python é muito divertido e interessante.")
print("sou novo na área de programação e estou animado para aprender.")
print("vai corinthians!")
print("vamos juntos nessa jornada de aprendizado!")
print("vamos aprender ADS")
print("python é legal")
